#This will prepare any wqp beta pull for use with IR automation code. 
#This example uses USGS data

library(tidyverse)
library(EPATADA)

#TADA required fields template
template <- TADA_GetTemplate()

#pull USGS data from wqp beta post 3/2/2024
#add required columns for TADA_AUTOCLEAN
usgs <- read_csv("Data/data_pull/USGS_Pull.csv") %>%
  filter(Org_Identifier == "USGS" & !is.na(Location_Latitude)) %>%
  mutate(ResultAnalyticalMethod.MethodUrl = "",
       SamplingDesignTypeCode = "",
       ProjectDescriptionText = "",
       ProjectFileUrl = "",
       AquiferName = "",
       ActivityStartDateTime = "",
       AquiferTypeName = "",
       LocalAqfrName = "",
       ConstructionDateText = "",
       WellDepthMeasure.MeasureValue = "",
       WellDepthMeasure.MeasureUnitCode = "",
       WellHoleDepthMeasure.MeasureValue = "",
       WellHoleDepthMeasure.MeasureUnitCode = "",
       ActivityDepthAltitudeReferencePointText="",
       ActivityEndDate="",
       ActivityEndTime.Time="",
       ActivityEndTime.TimeZoneCode="",
       ActivityEndDateTime="",
       ActivityConductingOrganizationText="",
       SampleAquifer="",
       ActivityLocation.LatitudeMeasure="",
       ActivityLocation.LongitudeMeasure="",
       ResultStatusIdentifier="",
       ResultWeightBasisText="",
       ResultTemperatureBasisText="",
       ResultParticleSizeBasisText="",
       USGSPCode="",
       BinaryObjectFileName="",
       BinaryObjectFileTypeCode="",
       AnalysisStartDate="",
       ResultDetectionQuantitationLimitUrl="",
       LabSamplePreparationUrl="",
       ActivityStartTime.TimeZoneCode_offset="",
       SourceMapScaleNumeric="",
       HorizontalAccuracyMeasure.MeasureValue="",
       HorizontalAccuracyMeasure.MeasureUnitCode="",
       HorizontalCollectionMethodName="",
       VerticalMeasure.MeasureValue="",
       VerticalMeasure.MeasureUnitCode="",
       VerticalAccuracyMeasure.MeasureValue="",
       VerticalAccuracyMeasure.MeasureUnitCode="",
       VerticalCollectionMethodName="",
       VerticalCoordinateReferenceSystemDatumName="",
       FormationTypeText="",
       ProjectMonitoringLocationWeightingUrl="",
       DrainageAreaMeasure.MeasureValue="",
       DrainageAreaMeasure.MeasureUnitCode="",
       ContributingDrainageAreaMeasure.MeasureValue="",
       ContributingDrainageAreaMeasure.MeasureUnitCode="",
       ProviderName="",
       LastUpdated="",
       ActivityEndTime.TimeZoneCode_offset="") %>%
  select(ActivityTypeCode = Activity_TypeCode,
         ActivityMediaName = Activity_Media,
         ActivityMediaSubdivisionName = Activity_MediaSubdivisionName,
         ResultSampleFractionText = Result_SampleFraction,
         CharacteristicName = Result_Characteristic,
         SubjectTaxonomicName = ResultBiological_Taxon,
         SampleTissueAnatomyName = ResultBiological_SampleTissueAnatomy,
         MethodSpeciationName = Result_MethodSpeciation,
         ActivityStartDate = Activity_StartDate,
         ActivityStartTime.Time = Activity_StartTime,
         ActivityStartTime.TimeZoneCode = Activity_StartTimeZone,
         ActivityStartDateTime, 
         ResultMeasureValue = Result_Measure,
         ResultMeasure.MeasureUnitCode = Result_MeasureUnit,
         ResultValueTypeName = Result_MeasureType,
         ResultDetectionConditionText = Result_ResultDetectionCondition,
         DetectionQuantitationLimitTypeName = DetectionLimit_TypeA,
         DetectionQuantitationLimitMeasure.MeasureValue = DetectionLimit_MeasureA,
         DetectionQuantitationLimitMeasure.MeasureUnitCode = DetectionLimit_MeasureUnitA,
         ResultDepthHeightMeasure.MeasureValue = ResultDepthHeight_Measure,
         ResultDepthHeightMeasure.MeasureUnitCode = ResultDepthHeight_MeasureUnit,
         ResultDepthAltitudeReferencePointText = ResultDepthHeight_AltitudeReferencePoint,
         ActivityRelativeDepthName = Activity_ActivityRelativeDepth,
         ActivityDepthHeightMeasure.MeasureValue = Activity_DepthHeightMeasure,
         ActivityDepthHeightMeasure.MeasureUnitCode = Activity_DepthHeightMeasureUnit,
         ActivityTopDepthHeightMeasure.MeasureValue = Activity_TopDepthMeasure,
         ActivityTopDepthHeightMeasure.MeasureUnitCode = Activity_TopDepthMeasureUnit,
         ActivityBottomDepthHeightMeasure.MeasureValue = Activity_BottomDepthMeasure,
         ActivityBottomDepthHeightMeasure.MeasureUnitCode = Activity_BottomDepthMeasureUnit,
         ResultTimeBasisText = Result_TimeBasis,
         StatisticalBaseCode = Result_StatisticalBase,
         ResultFileUrl = ResultAttachment_FileDownload,
         ResultAnalyticalMethod.MethodName = ResultAnalyticalMethod_Name,
         ResultAnalyticalMethod.MethodDescriptionText = ResultAnalyticalMethod_Description,
         ResultAnalyticalMethod.MethodIdentifier = ResultAnalyticalMethod_Identifier,
         ResultAnalyticalMethod.MethodIdentifierContext = ResultAnalyticalMethod_IdentifierContext,
         ResultAnalyticalMethod.MethodUrl  ,
         SampleCollectionMethod.MethodIdentifier = SampleCollectionMethod_Identifier,
         SampleCollectionMethod.MethodIdentifierContext = SampleCollectionMethod_IdentifierContext,
         SampleCollectionMethod.MethodName = SampleCollectionMethod_Name,
         SampleCollectionMethod.MethodDescriptionText = SampleCollectionMethod_Description,
         SampleCollectionEquipmentName = SampleCollectionMethod_EquipmentName,
         MeasureQualifierCode = SampleCollectionMethod_QualifierTypeName,
         ResultCommentText = DataQuality_ResultComment,
         ActivityCommentText = Activity_Comment,
         HydrologicCondition = Activity_HydrologicCondition,
         HydrologicEvent = Activity_HydrologicEvent,
         DataQuality.PrecisionValue = DataQuality_PrecisionValue,
         DataQuality.BiasValue = DataQuality_BiasValue,
         DataQuality.ConfidenceIntervalValue = DataQuality_ConfidenceIntervalValue,
         DataQuality.UpperConfidenceLimitValue = DataQuality_UpperConfidenceLimitValue,
         DataQuality.LowerConfidenceLimitValue = DataQuality_LowerConfidenceLimitValue,
         SamplingDesignTypeCode  ,
         LaboratoryName = LabInfo_Name,
         ResultLaboratoryCommentText = LabInfo_LaboratoryComment,
         ResultIdentifier = Result_MeasureIdentifier,
         ActivityIdentifier = Activity_ActivityIdentifier,
         OrganizationIdentifier = Org_Identifier,
         OrganizationFormalName = Org_FormalName,
         ProjectName = Project_Name,
         ProjectDescriptionText  ,
         ProjectIdentifier = Project_Identifier,
         ProjectFileUrl  ,
         QAPPApprovedIndicator = Project_QAPPApproved,
         QAPPApprovalAgencyName = Project_QAPPApprovalAgency,
         CountryCode = Location_CountryCode,
         StateCode = Location_StatePostalCode,
         CountyCode = Location_CountyCode,
         MonitoringLocationName = Location_Name,
         MonitoringLocationTypeName = Location_Type,
         MonitoringLocationDescriptionText = Location_Description,
         LatitudeMeasure = Location_Latitude,
         LongitudeMeasure = Location_Longitude,
         HorizontalCoordinateReferenceSystemDatumName = ActivityLocation_HorzCoordReferenceSystemDatum,
         HUCEightDigitCode = Location_HUCEightDigitCode,
         MonitoringLocationIdentifier = Location_Identifier,
         AquiferName  ,
         AquiferTypeName  ,
         LocalAqfrName  ,
         ConstructionDateText  ,
         WellDepthMeasure.MeasureValue  ,
         WellDepthMeasure.MeasureUnitCode  ,
         WellHoleDepthMeasure.MeasureValue  ,
         WellHoleDepthMeasure.MeasureUnitCode,
         ActivityDepthAltitudeReferencePointText,
         ActivityEndDate,
         ActivityEndTime.Time,
         ActivityEndTime.TimeZoneCode,
         ActivityEndDateTime,
         ActivityConductingOrganizationText,
         SampleAquifer,
         ActivityLocation.LatitudeMeasure,
         ActivityLocation.LongitudeMeasure,
         ResultStatusIdentifier,
         ResultWeightBasisText,
         ResultTemperatureBasisText,
         ResultParticleSizeBasisText,
         USGSPCode,
         BinaryObjectFileName,
         BinaryObjectFileTypeCode,
         AnalysisStartDate,
         ResultDetectionQuantitationLimitUrl,
         LabSamplePreparationUrl,
         ActivityStartTime.TimeZoneCode_offset,
         SourceMapScaleNumeric,
         HorizontalAccuracyMeasure.MeasureValue,
         HorizontalAccuracyMeasure.MeasureUnitCode,
         HorizontalCollectionMethodName,
         VerticalMeasure.MeasureValue,
         VerticalMeasure.MeasureUnitCode,
         VerticalAccuracyMeasure.MeasureValue,
         VerticalAccuracyMeasure.MeasureUnitCode,
         VerticalCollectionMethodName,
         VerticalCoordinateReferenceSystemDatumName,
         FormationTypeText,
         ProjectMonitoringLocationWeightingUrl,
         DrainageAreaMeasure.MeasureValue,
         DrainageAreaMeasure.MeasureUnitCode,
         ContributingDrainageAreaMeasure.MeasureValue,
         ContributingDrainageAreaMeasure.MeasureUnitCode,
         ProviderName,
         LastUpdated,
         ActivityEndTime.TimeZoneCode_offset)
         

#apply autoclean, fix org ID and activity codes
usgs_clean <- TADA_AutoClean(usgs) %>%
  mutate(OrganizationIdentifier = "USGS-AK") %>%
  mutate(ActivityTypeCode = case_when(
    ActivityTypeCode == "Sample - Routine, regular" ~ "Sample-Routine",
    ActivityTypeCode == "Sample - Routine, with an associated replicate"~"Sample - Routine",
    ActivityTypeCode == "Quality Control Sample - Equipment blank"~ "Quality Control Sample-Equipment Blank"
    ))
    
#save USGS data to data pull folder for data processing
write_csv(usgs_clean, 'Data/data_pull/test_26/data_pull_usgs.csv')

