---
title: "Summary AU Table Guide"
author: "Tetra Tech"
date: last-modified
date-format: "MMMM DD, YYYY"
format: docx
editor: visual
---

## Introduction

The following user guide pertains to the [*summary_au_table.R*](https://github.com/KateriSalk/Alaska_IR_Automation/blob/main/Code/7_Results/summary_au_table.R) script developed by Tetra Tech for the Alaska Department of Environmental Conservation (AK DEC). This guide assumes that the user has relatively recent versions of [R](https://www.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/) installed and that they are familiar with the R coding language. Please direct any questions regarding the usage of the *summary_au_table.R* script to Amber Crawford, AK DEC (amber.crawford\@alaska.gov).

### Purpose

The purpose of the *data_processing.R* script is to first conduct quality control and data wrangling on Water Quality Portal ([WQP](https://www.waterqualitydata.us/)) data downloaded using the [*data_pull.R*](https://github.com/KateriSalk/Alaska_IR_Automation/blob/main/Code/3_Data_Pull/data_pull.R) script. These steps heavily rely upon *TADA* functions as described below. WQ data are then matched to AK DEC's Assessment Units (AUs) using a crosswalk table. Monitoring locations with WQ data that are not in the crosswalk table are assigned to AUs using spatial joins to existing AU shapefiles and the joins can be evaluated using interactive mapping. Finally, data sufficiency is determined for each AU/pollutant combination using a data sufficiency lookup table for each designated use and pollutant.

## Required Packages

The required packages for the *data_processing.R* code are [*TADA*](https://github.com/USEPA/TADA), [*tidyverse*](https://www.tidyverse.org/)*, [leaflet](https://rstudio.github.io/leaflet/), [scales](https://scales.r-lib.org/),* and [*sf*](https://r-spatial.github.io/sf/)*.* Installation for the *TADA* and *tidyverse* packages can be found in the Data Pull Guide. Below is a code chunk that demonstrates how to install and load these packages. If you work from using a Virtual Private Network (VPN), you may have trouble downloading packages, and if so, simply turn the VPN off before package download.

`{r} #| output: false #| eval: false # install.packages('leaflet') library(leaflet)  # install.packages('scales') library(scales)  # install.packages('sf') library(sf)  library(TADA) library(sf)}`

## Required Inputs

This code has specific exterior files that are required for it to run. The inputs are listed below. Note, only the outputs from *data_pull.R* are loaded at the beginning of the script, whereas all others are loaded when needed farther into the script.

| File Name                                              | Purpose                                      | Source                   |
|--------------------------------------------------------|----------------------------------------------|--------------------------|
| .CSV outputs (varies by site types from *data_pull.R*) | WQ data to be processed.                     | WQP (via *data_pull.R*). |
| WQ_Column_Manager.csv                                  | Quickly subset WQ dataset fields.            | Tetra Tech               |
| ML_AU_Crosswalk.csv                                    | Crosswalk Monitoring Locations with AUs/     | AK DEC                   |
| AK_DataSufficiency_Crosswalk_20231012.csv              | Determine data sufficiency per AU/pollutant. | AK DEC                   |
| Beaches.shp                                            | Beaches AU shapefile for mapping.            | AK DEC                   |
| Lakes.shp                                              | Lakes AU shapefile for mapping.              | AK DEC                   |
| MAUs_FINAL_2023.shp                                    | Marine AU shapefile for mapping.             | AK DEC                   |
| Rivers.shp                                             | Rivers AU shapefile for mapping.             | AK DEC                   |
| cb_2018_us_state_500k.shp                              | US States shapefile for mapping.             | Tetra Tech               |

: Exterior files required by data_processing.R to function properly, the purpose of each file within the code, and their source.

## Load Data
